[package]
name = "macc"
version = "0.9.1"
authors = ["32byte <xlebedenko@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
clap = { version = "3.0.14", features = ["derive"] }
macc_lib = { path = "../lib" }
serde_json = "1.0.59"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
reqwest = "0.11.9"
bincode = "1.3.3"
colored = "2.0.0"
chrono = "0.4.19"
log = "0.4.14"
local-ip-address = "0.4.4"
ctrlc = "3.2.1"