[package]
name = "macc"
version = "0.9.1"
authors = ["32byte <xlebedenko@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
# rocket = { version = "0.5.0-rc.1", features = ["json"] }
macc_lib = { path = "../lib" }
# reqwest = { version = "0.11.7", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
# bincode = "1.2.1"
colored = "2.0.0"
chrono = "0.4.19"
# clap = "2.33.3"
log = "0.4.14"

# [target.'cfg(unix)'.dependencies]
# termion = "1.5.6"