[package]
name = "macc_wasm"
version = "0.1.0"
edition = "2018"

[lib]
path = "rust-src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
macc_lib = { path = "../lib" }
serde_json = "1.0.59"
wasm-bindgen = "0.2"